meta:
  chembl_release: ChEMBL 36
  source_urls:
  - https://www.ebi.ac.uk/chembl/api/data/docs
  - https://chembl.blogspot.com/2025/09/chembl-36-is-out.html
  - https://chembl.blogspot.com/2020/10/data-checks.html
  - https://github.com/chembl/GLaDOS-docs/blob/master/frequently-asked-questions/chembl-data-questions.md
  updated_at: '2025-11-07'
values:
- id: IC50
  aliases:
  - IC-50
  - IC 50
  - IC_50
  status: active
- id: Ki
  aliases:
  - Káµ¢
  - KI
  - Ki (inhibition constant)
  - INHIBITION CONSTANT KI
  status: active
- id: EC50
  aliases:
  - EC-50
  - EC 50
  - EC_50
  status: deprecated
- id: Kd
  aliases:
  - KD
  status: deprecated
- id: GI50
  aliases: []
  status: deprecated
- id: Potency
  aliases:
  - POT
  status: deprecated
rules:
  normalization: trim|upper|map_aliases_to_id
