extends:
  - ../base.yaml
  - ../includes/cache.yaml

pipeline:
  name: "dev"
  entity: "development"

http:
  global:
    timeout_sec: 30.0
    retries:
      total: 2
      backoff_multiplier: 1.5
      backoff_max: 30.0
    rate_limit:
      max_calls: 10
      period: 10.0

cache:
  ttl: 3600

qc:
  severity_threshold: "error"
